spring.application.name=NflScoreLiquibase
spring.datasource.url=jdbc:postgresql://localhost:5433/NFLScoreDatabase
spring.datasource.username=postgres
spring.datasource.password=Admin123
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update # or create, create-drop, none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/liquibase-changelog.xml
